import {TASK_STATUSES,STATUS_LABEL,STATUS_CLASS,uid,allTasks,calcProgress,getNextTask,daysUntil,caseMatches} from './core.js';

const $=s=>document.querySelector(s), main=$('#main'), sheet=$('#sheet'), sheetContent=$('#sheetContent'), toast=$('#toast');
const KEY='workflow-map-state-v2';
let tab='home', selectedCaseId=null;
let state=load();
function emptyState(){return {version:2,currentWorkId:null,works:[]}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||emptyState()}catch{return emptyState()}}
function save(msg='保存しました'){localStorage.setItem(KEY,JSON.stringify(state));render();showToast(msg)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showToast(m){toast.textContent=m;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),1800)}
function closeSheet(){sheet.classList.add('hidden');sheetContent.innerHTML=''}
function openSheet(html){sheetContent.innerHTML=html;sheet.classList.remove('hidden')}
sheet.addEventListener('click',e=>{if(e.target===sheet)closeSheet()});
function currentWork(){return state.works.find(w=>w.id===state.currentWorkId)||state.works[0]||null}
function ensureWork(){const w=currentWork();if(w&&!state.currentWorkId)state.currentWorkId=w.id;return w}
function person(){const w=currentWork();return localStorage.getItem('workflow-map-person')||w?.members?.[0]||''}
function setPerson(v){localStorage.setItem('workflow-map-person',v)}
function fmtDate(v){if(!v)return'';const d=new Date(v+'T00:00:00');return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`}
function allWorkTasks(w){return (w?.cases||[]).filter(c=>c.status!=='archived').flatMap(c=>allTasks(c).map(t=>({...t,caseId:c.id,caseTitle:c.title})))}
function setTab(t){tab=t;selectedCaseId=null;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$('#pageTitle').textContent={home:'ホーム',cases:'案件',mine:'私の担当',history:'履歴',settings:'設定'}[t];render()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('#helpBtn').onclick=()=>location.href='manual.html';
$('#syncBtn').onclick=()=>showToast('この公開版は端末保存モードです');
$('#fab').onclick=()=>currentWork()?openNewCase():openNewWork();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});

function render(){const w=ensureWork();if(!w)return renderWelcome();if(selectedCaseId)return renderCase();if(tab==='home')renderHome();if(tab==='cases')renderCases();if(tab==='mine')renderMine();if(tab==='history')renderHistory();if(tab==='settings')renderSettings()}
function renderWelcome(){main.innerHTML=`<section class="hero"><div class="kicker">WORKFLOW MAP</div><h2>最初のワークを作りましょう</h2><p>家庭、総務部、イベント、学校業務など、用途ごとに自由な名前を付けられます。</p></section><button class="button" id="firstWork">＋ ワークを作る</button>`;$('#firstWork').onclick=openNewWork}
function workBar(w){return `<div class="settings-card row"><div><small>現在のワーク</small><strong style="display:block">${esc(w.name)}</strong></div><button class="button secondary small" id="switchWork">切替</button></div>`}
function renderHome(){const w=currentWork(), tasks=allWorkTasks(w), active=w.cases.filter(c=>c.status!=='archived'), mine=tasks.filter(t=>(t.assignees||[]).includes(person())&&!['done','not_needed'].includes(t.status)), unassigned=tasks.filter(t=>!(t.assignees||[]).length&&!['done','not_needed'].includes(t.status)), waiting=tasks.filter(t=>t.status==='waiting'), due=tasks.filter(t=>t.dueDate&&!['done','not_needed'].includes(t.status)&&daysUntil(t.dueDate)<=7), done=tasks.filter(t=>t.status==='done').slice(-5).reverse();main.innerHTML=workBar(w)+`<section class="hero"><div class="kicker">今日見るところ</div><h2>${active.length?`${active.length}件の案件を進行中`:'案件を追加しましょう'}</h2><p>現在地、担当、待ち状態を1画面で確認します。</p></section><div class="overview-grid">${ov('🔴','期限間近',due.length)}${ov('👤','自分の担当',mine.length)}${ov('❓','担当未定',unassigned.length)}${ov('⏳','相手待ち',waiting.length)}${ov('✅','最近完了',done.length)}</div><div class="section-head"><h2>案件</h2><small>${active.length}件</small></div>${active.map(caseCard).join('')||'<div class="empty">案件はまだありません。</div>'}`;bindCaseLinks();$('#switchWork').onclick=openWorkSwitcher}
function ov(icon,label,n){return `<div class="overview-card"><span>${icon}</span><small>${label}</small><strong>${n}</strong></div>`}
function caseCard(c){const next=getNextTask(c),p=calcProgress(c);return `<article class="case-card" data-case="${c.id}"><div class="case-top"><h3>${esc(c.title)}</h3><span class="pill">${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div>${next?`<div class="next-box"><span class="label">次にやること</span><strong>${esc(next.title)}</strong><div class="meta"><span class="status ${STATUS_CLASS[next.status]}">${STATUS_LABEL[next.status]}</span><span class="pill">${esc((next.assignees||[]).join('・')||'担当未定')}</span></div></div>`:'<div class="next-box"><strong>すべて完了</strong></div>'}</article>`}
function bindCaseLinks(){main.querySelectorAll('[data-case]').forEach(x=>x.onclick=()=>{selectedCaseId=x.dataset.case;render()})}
function renderCases(){const w=currentWork();main.innerHTML=workBar(w)+`<input class="search" id="caseSearch" placeholder="案件・メモを検索"> <div id="caseList">${w.cases.map(caseCard).join('')||'<div class="empty">案件はまだありません。</div>'}</div>`;$('#switchWork').onclick=openWorkSwitcher;bindCaseLinks();$('#caseSearch').oninput=e=>{const q=e.target.value;$('#caseList').innerHTML=w.cases.filter(c=>caseMatches(c,q)).map(caseCard).join('')||'<div class="empty">見つかりません。</div>';bindCaseLinks()}}
function renderMine(){const w=currentWork(), p=person(), tasks=allWorkTasks(w).filter(t=>(t.assignees||[]).includes(p)&&!['done','not_needed'].includes(t.status));main.innerHTML=workBar(w)+`<div class="settings-card"><strong>あなた：${esc(p||'未選択')}</strong><button class="button secondary small" id="pickPerson" style="margin-left:8px">変更</button></div>${tasks.map(taskRow).join('')||'<div class="empty">担当タスクはありません。</div>'}`;$('#switchWork').onclick=openWorkSwitcher;$('#pickPerson').onclick=openPersonPicker;bindTaskRows()}
function taskRow(t){return `<article class="case-card" data-open-case="${t.caseId}"><small>${esc(t.caseTitle)} / ${esc(t.stageTitle||'')}</small><h3>${esc(t.title)}</h3><div class="meta"><span class="status ${STATUS_CLASS[t.status]}">${STATUS_LABEL[t.status]}</span>${t.dueDate?`<span class="pill">期限 ${fmtDate(t.dueDate)}</span>`:''}</div></article>`}
function bindTaskRows(){main.querySelectorAll('[data-open-case]').forEach(x=>x.onclick=()=>{selectedCaseId=x.dataset.openCase;render()})}
function renderHistory(){const w=currentWork();const items=[];for(const c of w.cases){for(const n of c.notes||[])items.push({date:n.createdAt||n.date,title:n.title||'メモ',body:n.body||'',caseTitle:c.title});for(const t of allTasks(c))if(t.status==='done')items.push({date:t.completedAt||t.updatedAt,title:`完了：${t.title}`,body:'',caseTitle:c.title})}items.sort((a,b)=>(b.date||'').localeCompare(a.date||''));main.innerHTML=workBar(w)+(items.map(i=>`<div class="note"><small>${esc(i.caseTitle)} ・ ${fmtDate((i.date||'').slice(0,10))}</small><strong style="display:block">${esc(i.title)}</strong><p>${esc(i.body)}</p></div>`).join('')||'<div class="empty">履歴はまだありません。</div>');$('#switchWork').onclick=openWorkSwitcher}
function renderSettings(){const w=currentWork();main.innerHTML=workBar(w)+`<section class="settings-card"><h3>ワーク</h3><button class="button secondary" id="renameWork">名前を変更</button> <button class="button secondary" id="newWork">＋ 新しいワーク</button></section><section class="settings-card"><h3>メンバー</h3><p>${(w.members||[]).map(esc).join('・')||'まだ登録されていません。'}</p><button class="button secondary" id="manageMembers">メンバーを編集</button></section><section class="settings-card"><h3>データ</h3><p>現在はこの端末のブラウザに保存します。Supabase接続後はチーム共有へ切り替えます。</p><button class="button secondary" id="exportBtn">JSONを書き出す</button> <label class="button secondary" for="importFile">JSONを読み込む</label><input id="importFile" type="file" accept="application/json" hidden></section><section class="settings-card"><a class="button secondary" href="manual.html">？ 使い方</a></section>`;$('#switchWork').onclick=openWorkSwitcher;$('#renameWork').onclick=()=>renameWork(w);$('#newWork').onclick=openNewWork;$('#manageMembers').onclick=()=>manageMembers(w);$('#exportBtn').onclick=exportJson;$('#importFile').onchange=importJson}
function renderCase(){const w=currentWork(),c=w.cases.find(x=>x.id===selectedCaseId);if(!c){selectedCaseId=null;return render()}main.innerHTML=`<button class="button secondary small" id="back">← 戻る</button><div class="section-head"><h2>${esc(c.title)}</h2><button class="button secondary small" id="editCase">編集</button></div>${c.goal?`<div class="settings-card"><small>ゴール</small><strong style="display:block">${esc(c.goal)}</strong></div>`:''}${c.stages.map((s,si)=>stageHtml(c,s,si)).join('')||'<div class="empty">工程はまだありません。</div>'}<div class="button-row"><button class="button secondary" id="addStage">＋ 工程</button><button class="button secondary" id="addNote">＋ メモ</button></div>${(c.notes||[]).slice().reverse().map(n=>`<div class="note"><small>${fmtDate((n.date||'').slice(0,10))}</small><strong style="display:block">${esc(n.title)}</strong><p>${esc(n.body)}</p></div>`).join('')}`;$('#back').onclick=()=>{selectedCaseId=null;render()};$('#editCase').onclick=()=>editCase(c);$('#addStage').onclick=()=>addStage(c);$('#addNote').onclick=()=>addNote(c);main.querySelectorAll('[data-add-task]').forEach(b=>b.onclick=()=>editTask(c,b.dataset.addTask));main.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>editTask(c,b.dataset.stage,b.dataset.task))}
function stageHtml(c,s,i){return `<section class="stage-card"><header><h3>${esc(s.title)}</h3></header>${s.tasks.map(t=>`<article class="task-card" data-task="${t.id}" data-stage="${s.id}"><h4>${esc(t.title)}</h4><div class="meta"><span class="status ${STATUS_CLASS[t.status]}">${STATUS_LABEL[t.status]}</span><span class="pill">${esc((t.assignees||[]).join('・')||'担当未定')}</span></div></article>`).join('')||'<p>タスクはまだありません。</p>'}<button class="button secondary small" data-add-task="${s.id}">＋ タスク</button></section>`}
function openNewWork(){openSheet(`<h2>＋ ワークを作る</h2><form id="workForm"><div class="field"><label>ワーク名</label><input id="workName" required placeholder="例：総務部 2026"></div><button class="button">作成</button></form>`);$('#workForm').onsubmit=e=>{e.preventDefault();const w={id:uid('work'),name:$('#workName').value.trim(),members:[],cases:[],createdAt:new Date().toISOString()};state.works.push(w);state.currentWorkId=w.id;closeSheet();save('ワークを作成しました')}}
function openWorkSwitcher(){openSheet(`<h2>ワークを切り替える</h2>${state.works.map(w=>`<button class="button secondary" data-work="${w.id}" style="display:block;width:100%;margin:8px 0">${esc(w.name)}</button>`).join('')}<button class="button" id="addWorkHere">＋ 新しいワーク</button>`);sheetContent.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{state.currentWorkId=b.dataset.work;selectedCaseId=null;closeSheet();save('ワークを切り替えました')});$('#addWorkHere').onclick=()=>{closeSheet();openNewWork()}}
function renameWork(w){openSheet(`<h2>ワーク名を変更</h2><form id="renameForm"><input class="search" id="renameValue" value="${esc(w.name)}" required><button class="button">保存</button></form>`);$('#renameForm').onsubmit=e=>{e.preventDefault();w.name=$('#renameValue').value.trim();closeSheet();save('ワーク名を変更しました')}}
function manageMembers(w){openSheet(`<h2>メンバーを編集</h2><form id="memberForm"><div class="field"><label>1行に1人</label><textarea id="memberValue">${esc((w.members||[]).join('\n'))}</textarea></div><button class="button">保存</button></form>`);$('#memberForm').onsubmit=e=>{e.preventDefault();w.members=$('#memberValue').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);closeSheet();save('メンバーを更新しました')}}
function openPersonPicker(){const w=currentWork();openSheet(`<h2>あなたを選択</h2>${(w.members||[]).map(p=>`<button class="button secondary" data-person="${esc(p)}" style="display:block;width:100%;margin:8px 0">${esc(p)}</button>`).join('')||'<p>設定でメンバーを登録してください。</p>'}`);sheetContent.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{setPerson(b.dataset.person);closeSheet();render()})}
function openNewCase(){openSheet(`<h2>＋ 案件を作る</h2><form id="caseForm"><div class="field"><label>案件名</label><input id="caseName" required></div><div class="field"><label>ゴール</label><textarea id="caseGoal"></textarea></div><button class="button">作成</button></form>`);$('#caseForm').onsubmit=e=>{e.preventDefault();currentWork().cases.push({id:uid('case'),title:$('#caseName').value.trim(),goal:$('#caseGoal').value.trim(),summary:'',status:'active',stages:[],notes:[],createdAt:new Date().toISOString()});closeSheet();save('案件を作成しました')}}
function editCase(c){openSheet(`<h2>案件を編集</h2><form id="editCaseForm"><div class="field"><label>案件名</label><input id="ecName" value="${esc(c.title)}" required></div><div class="field"><label>ゴール</label><textarea id="ecGoal">${esc(c.goal||'')}</textarea></div><button class="button">保存</button></form>`);$('#editCaseForm').onsubmit=e=>{e.preventDefault();c.title=$('#ecName').value.trim();c.goal=$('#ecGoal').value.trim();closeSheet();save('案件を更新しました')}}
function addStage(c){openSheet(`<h2>＋ 工程</h2><form id="stageForm"><input class="search" id="stageName" required placeholder="工程名"><button class="button">追加</button></form>`);$('#stageForm').onsubmit=e=>{e.preventDefault();c.stages.push({id:uid('stage'),title:$('#stageName').value.trim(),tasks:[]});closeSheet();save('工程を追加しました')}}
function editTask(c,stageId,taskId=null){const s=c.stages.find(x=>x.id===stageId),t=taskId?s.tasks.find(x=>x.id===taskId):{title:'',status:'unassigned',assignees:[],dueDate:'',memo:''},w=currentWork();openSheet(`<h2>${taskId?'タスクを編集':'＋ タスク'}</h2><form id="taskForm"><div class="field"><label>タスク名</label><input id="tName" value="${esc(t.title)}" required></div><div class="field"><label>状態</label><select id="tStatus">${TASK_STATUSES.map(([v,l])=>`<option value="${v}" ${t.status===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>担当者</label>${(w.members||[]).map(p=>`<label class="check"><input type="checkbox" name="assignee" value="${esc(p)}" ${(t.assignees||[]).includes(p)?'checked':''}>${esc(p)}</label>`).join('')||'<p>設定でメンバーを登録できます。</p>'}</div><div class="field"><label>期限</label><input type="date" id="tDue" value="${esc(t.dueDate||'')}"></div><div class="field"><label>メモ</label><textarea id="tMemo">${esc(t.memo||'')}</textarea></div><button class="button">保存</button></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const a=[...sheetContent.querySelectorAll('input[name=assignee]:checked')].map(x=>x.value),st=$('#tStatus').value,obj=taskId?t:{id:uid('task'),createdAt:new Date().toISOString()};Object.assign(obj,{title:$('#tName').value.trim(),status:st,assignees:a,dueDate:$('#tDue').value,memo:$('#tMemo').value.trim(),updatedAt:new Date().toISOString(),completedAt:st==='done'?(obj.completedAt||new Date().toISOString()):null});if(!taskId)s.tasks.push(obj);closeSheet();save('タスクを保存しました')}}
function addNote(c){openSheet(`<h2>＋ メモ</h2><form id="noteForm"><div class="field"><label>見出し</label><input id="nTitle" required></div><div class="field"><label>内容</label><textarea id="nBody"></textarea></div><button class="button">保存</button></form>`);$('#noteForm').onsubmit=e=>{e.preventDefault();c.notes.push({id:uid('note'),title:$('#nTitle').value.trim(),body:$('#nBody').value.trim(),date:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()});closeSheet();save('メモを追加しました')}}
function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`workflow-map-${new Date().toISOString().slice(0,10)}.json`;a.click()}
function importJson(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.works))throw new Error('形式が違います');state=d;save('データを読み込みました')}catch(err){alert('読み込めません：'+err.message)}};r.readAsText(f)}
render();
